version: '2'

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:latest
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_PASSWORD=asdf
    volumes:
      - type: bind
        source: ./persist-storage
        target: /gempmq

        
networks:
  default:
    external:
      name: gemp_1_gemp_net_1
    
